language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - easy_install distribute
  - pip install -r requirements.txt

# command to run Doctests
script: pytest --doctest-modules