language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - sudo pip3 install --upgrade pip setuptools wheel
  - sudo pip3 -r requirements.txt

# command to run Doctests
script: pytest --doctest-modules